### ISSUE TITLE
Cannot run application from development environment.

### ISSUE THREAD

**Issue by cN3rd** [mpvqc/mpvQC#47]
Hi,

I followed the developer instructions, and setup a development environment for this project as the instructions mention.

After sourcing `libmpv` from the source you use in the CI, I tried running the app via `main.py` and got the following output:
```
QQmlApplicationEngine failed to load component
file::/qml/main.qml:25:1: Type MpvqcApplication unavailable
qrc:/qml/app/MpvqcApplication.qml:36:41: Type MpvqcManager unavailable
qrc:/qml/manager/MpvqcManager.qml:39:14: Array<url> is not a type
```

Tried it on WSL2, got the same error.

**Comment by trin94** [comment]
Hi @cN3rd,

I could reproduce the issue. When I downgraded PySide6 from **6.6.1** to **6.6.0**, I could get it to work again. Seems like there was a change that breaks QML types or does some verification now.

In order to get it to work, do the following:

1. Change `PySide6>=6.6.0` to `PySide6==6.6.0` in the `requirements.txt`
2. Delete the `venv` directory
3. Setup the venv again following [the guide](https://github.com/mpvqc/mpvQC/blob/main/docs/developer/dev-setup-windows.md)
4. Run `make develop-build`
5. Run `python main.py`

Let me know if this works for you 😃 

Best regards
Elias

**Comment by cN3rd** [comment]
That worked for me too. Thank you!

**Comment by trin94** [comment]
The application now runs with PySide 6.6.1 (#57) :)
